name: Issue Activity

on:
  issue_comment:
    types: [created, edited, deleted]
    
jobs:
  send-mail:
    runs-on: ubuntu-latest
    name: Send email when issue created/edited/deleted
    steps:
      - name: Send Mail Action
        id: sendmail
        uses: vineetchoudhary/mailgun-action@master
        with:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: sandboxb722719f9048484caf21b7386d808f56.mailgun.org    
          to: shubprasain@hotmail.com
          subject: 'Issue Activity'
          body: '<p><b>Body</b> - {{  }} <br /><br /><b>Issue Activity</b> - {{  }}.  <br /><br /><b>URL</b> - {{  }}  <br /><br /><b>By</b> - {{ }}</p>' 
      - name: Send Mail Action Response
        run: echo "${{ }}" 
